# Load schema to get editor completions
"$schema" = "https://starship.rs/config-schema.json"

# Blank line between shell prompts
add_newline = true

[character]
success_symbol = '[\$](bold white)'
error_symbol = '[\$](bold red)'
vicmd_symbol = '[:](bold white)'

[directory]
truncate_to_repo = false
truncation_length = 10
truncation_symbol = '.../'
style = 'bold blue'

[git_status]
style = 'bold yellow'
ahead = 'â†‘ '
behind = 'â†“ '
diverged = 'â†‘â†“ '
deleted = 'Ã—'

### From no-nerd-font preset ###
[battery]
full_symbol = "â€¢ "
charging_symbol = "â‡¡ "
discharging_symbol = "â‡£ "
unknown_symbol = "â“ "
empty_symbol = "â— "

[erlang]
symbol = "â“” "

[nodejs]
symbol = "[â¬¢](bold green) "

[pulumi]
symbol = "ğŸ§Š "

[typst]
symbol = "t "
### End no-nerd-font preset ###
